/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define AUDIORESAMPLE_FORMAT_AUTO

#define DEFAULT_AUDIOSINK "autoaudiosink"

#define DEFAULT_VIDEOSINK "autovideosink"

#define DISABLE_ORC 1

#define GETTEXT_PACKAGE "gst-plugins-base-1.0"

#define GIO_LIBDIR "/home/openhd/gst-android/prefix/aarch64/lib"

#define GIO_MODULE_DIR "/home/openhd/gst-android/prefix/aarch64/lib/gio/modules"

#define GIO_PREFIX "/home/openhd/gst-android/prefix/aarch64"

#define GST_API_VERSION "1.0"

#define GST_DATADIR "/home/openhd/gst-android/prefix/aarch64/share"

#define GST_INSTALL_PLUGINS_HELPER "/home/openhd/gst-android/prefix/aarch64/libexec/gst-install-plugins-helper"

#define GST_LICENSE "LGPL"

#define GST_PACKAGE_NAME "GStreamer Base Plug-ins git"

#define GST_PACKAGE_ORIGIN "Unknown package origin"

#define HAVE_CPU_AARCH64 1

#define HAVE_DLFCN_H 1

#define HAVE_EMMINTRIN_H 1

#define HAVE_GIO_UNIX_2_0

#define HAVE_GL 1

#define HAVE_GMTIME_R 1

#define HAVE_INTTYPES_H 1

#undef HAVE_ISO_CODES

#undef HAVE_LIBDRM

#define HAVE_LINUX_DMA_BUF_H 1

#define HAVE_LINUX_TCP_INFO

#define HAVE_LOCALTIME_R 1

#define HAVE_LOG2 1

#define HAVE_LRINTF 1

#define HAVE_MEMMEM 1

#define HAVE_MEMORY_H 1

#define HAVE_MMAP 1

#define HAVE_NETINET_IN_H 1

#define HAVE_NETINET_TCP_H 1

#undef HAVE_OGG

#define HAVE_SMMINTRIN_H 1

#define HAVE_STDINT_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_SYS_WAIT_H 1

#define HAVE_UNISTD_H 1

#undef HAVE_VALGRIND

#undef HAVE_X11

#undef HAVE_XI2

#define HAVE_XMMINTRIN_H 1

#undef HAVE_XSHM

#define HAVE_ZLIB

#define LOCALEDIR "/home/openhd/gst-android/prefix/aarch64/share/locale"

#define PACKAGE "gst-plugins-base"

#define PACKAGE_VERSION "1.27.1.1"

#define SIZEOF_CHAR 1

#define SIZEOF_INT 4

#define SIZEOF_LONG 8

#define SIZEOF_SHORT 2

#define SIZEOF_VOIDP 8

#define TARGET_CPU "armv8-a"

#define VERSION "1.27.1.1"

