name: android-gst-full

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  API_LEVEL: "35"
  NDK_VERSION: "r27c"

  WORK_ROOT: ${{ github.workspace }}
  NDK_DIR: ${{ github.workspace }}/.ndk/ndk-r27c

  QT_VERSION: "6.9.1"
  QT_HOST_DIR: ${{ github.workspace }}/.qt-host/6.9.1/gcc_64
  QT_ANDROID_DIR: ${{ github.workspace }}/.qt-android/Qt/6.9.1/android_arm64_v8a

  PREFIX: ${{ github.workspace }}/prefix/aarch64
  SRC_DIR: ${{ github.workspace }}/src

  MESON_OPTIONS: >
    -Dauto_features=disabled
    -Dintrospection=disabled
    -Dtests=disabled
    -Dexamples=disabled
    -Dgtk_doc=disabled
    -Dgpl=enabled
    -Dlibav=enabled
    -Dgood=enabled
    -Dgst-plugins-base:app=enabled
    -Dgst-plugins-base:playback=enabled
    -Dgst-plugins-base:video=enabled
    -Dgst-plugins-base:audio=enabled
    -Dgst-plugins-base:typefind=enabled
    -Dgst-plugins-base:codecparsers=enabled
    -Dgst-plugins-base:gl=enabled
    -Dgst-full=enabled
    -Dgst-full-target-type=static_library
    -Dgst-full-libraries=app,video,audio,gl,codecparsers
    -Dgst-plugins-good:qt6=enabled

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false

      # ---------- CACHES ----------
      - name: Restore ccache cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ccache-${{ runner.os }}-${{ env.NDK_VERSION }}-${{ env.API_LEVEL }}-${{ env.QT_VERSION }}-${{ hashFiles('android-aarch64.ini','subprojects/**','**/meson.build','**/meson_options.txt','.github/workflows/android-gst-full.yml') }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ env.NDK_VERSION }}-${{ env.API_LEVEL }}-${{ env.QT_VERSION }}-

      - name: Restore NDK
        uses: actions/cache@v4
        with:
          path: ${{ env.NDK_DIR }}
          key: ndk-${{ runner.os }}-${{ env.NDK_VERSION }}

      - name: Restore Qt host
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.qt-host
          key: qt-host-${{ runner.os }}-${{ env.QT_VERSION }}

      - name: Restore Qt android
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.qt-android
          key: qt-android-${{ runner.os }}-${{ env.QT_VERSION }}-arm64v8a

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt','.github/workflows/android-gst-full.yml') }}
          restore-keys: |
            pip-${{ runner.os }}-

      # ---------- SETUP ----------
      - name: Install base deps (incl. EGL/OpenGL for qsb)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential python3 python3-pip git cmake ninja-build \
            pkg-config yasm curl ca-certificates unzip \
            autoconf automake libtool ccache \
            libegl1 libopengl0
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user "meson>=1.4" "aqtinstall==3.3.0"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure ccache
        run: |
          mkdir -p ~/.cache/ccache
          ccache --set-config=cache_dir=~/.cache/ccache
          ccache --max-size=10G
          ccache --set-config=compression=true
          ccache --set-config=compiler_check=content
          ccache --zero-stats || true

      - name: Install / restore Android NDK r27c
        run: |
          if [ ! -d "${NDK_DIR}" ]; then
            mkdir -p "${WORK_ROOT}/.ndk"
            cd "${WORK_ROOT}/.ndk"
            curl -L -o ndk.zip https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip
            unzip -q ndk.zip
            mv android-ndk-${NDK_VERSION} ndk-${NDK_VERSION}
          fi
          echo "ANDROID_NDK=${NDK_DIR}" >> $GITHUB_ENV

      - name: Install / restore Qt (host + android)
        run: |
          # Host Qt
          if [ ! -d "${QT_HOST_DIR}" ]; then
            python3 -m aqt install-qt linux desktop "${QT_VERSION}" linux_gcc_64 -O "${WORK_ROOT}/.qt-host"
          fi
          # Android Qt
          if [ ! -d "${QT_ANDROID_DIR}" ]; then
            python3 -m aqt install-qt linux android "${QT_VERSION}" android_arm64_v8a -O "${WORK_ROOT}/.qt-android/Qt"
          fi

      - name: Bridge Android qmake6 wrapper to host Qt (symlink + PATH)
        run: |
          set -eux
          mkdir -p "${GITHUB_WORKSPACE}/.qt-android/Qt/${QT_VERSION}"
          ln -sfn "${QT_HOST_DIR}" "${GITHUB_WORKSPACE}/.qt-android/Qt/${QT_VERSION}/gcc_64"
          echo "${QT_ANDROID_DIR}/bin:${QT_HOST_DIR}/bin:${QT_HOST_DIR}/libexec" >> "$GITHUB_PATH"
          echo "QT_HOST_PATH=${QT_HOST_DIR}" >> $GITHUB_ENV

      - name: Prepare env
        run: |
          mkdir -p "${PREFIX}" "${SRC_DIR}"
          echo "PKG_CONFIG_LIBDIR=${PREFIX}/lib/pkgconfig:${PREFIX}/share/pkgconfig:${PREFIX}/lib/gstreamer-1.0/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig" >> $GITHUB_ENV

      # ---------- BUILD DEPS ----------
      - name: Build x264 (static, PIC, with ccache)
        working-directory: ${{ env.SRC_DIR }}
        run: |
          set -eux
          git clone --depth=1 https://code.videolan.org/videolan/x264.git
          cd x264
          TOOL="${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64"
          API="${API_LEVEL}"
          TARGET=aarch64-linux-android
          export CC="ccache ${TOOL}/bin/${TARGET}${API}-clang"
          export AR="${TOOL}/bin/llvm-ar"
          export RANLIB="${TOOL}/bin/llvm-ranlib"
          export STRIP="${TOOL}/bin/llvm-strip"
          ./configure \
            --host="${TARGET}" \
            --sysroot="${TOOL}/sysroot" \
            --prefix="${PREFIX}" \
            --enable-static \
            --enable-pic \
            --disable-cli
          make -j"$(nproc)"
          make install
          PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig" pkg-config --modversion x264

      - name: Build FFmpeg 7.1 (static, with ccache)
        working-directory: ${{ env.SRC_DIR }}
        run: |
          set -eux
          curl -L -o ffmpeg-7.1.tar.xz https://www.ffmpeg.org/releases/ffmpeg-7.1.tar.xz
          tar -xf ffmpeg-7.1.tar.xz
          cd ffmpeg-7.1
          TOOL="${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64"
          API="${API_LEVEL}"
          TARGET=aarch64-linux-android
          SYSROOT="${TOOL}/sysroot"
          CC="ccache ${TOOL}/bin/${TARGET}${API}-clang"
          CXX="ccache ${TOOL}/bin/${TARGET}${API}-clang++"
          AR="${TOOL}/bin/llvm-ar"
          RANLIB="${TOOL}/bin/llvm-ranlib"
          STRIP="${TOOL}/bin/llvm-strip"
          PKG_CONFIG_LIBDIR="${PKG_CONFIG_LIBDIR}" \
          ./configure \
            --prefix="${PREFIX}" \
            --pkg-config-flags="--static" \
            --ar="${AR}" --ranlib="${RANLIB}" --strip="${STRIP}" \
            --cc="${CC}" --cxx="${CXX}" \
            --target-os=android --arch=aarch64 --cpu=armv8-a \
            --sysroot="${SYSROOT}" --enable-cross-compile \
            --enable-gpl --enable-libx264 \
            --enable-static --disable-shared \
            --disable-programs --disable-doc --disable-debug
          make -j"$(nproc)"
          make install

      # ---------- MESON CROSS + NATIVE ----------
      - name: Create Meson cross file (android-aarch64.ini)
        working-directory: ${{ github.workspace }}
        run: |
          TOOL="${NDK_DIR}/toolchains/llvm/prebuilt/linux-x86_64"
          API="${API_LEVEL}"
          TARGET=aarch64-linux-android
          cat > android-aarch64.ini <<EOF
          [binaries]
          c = ['ccache', '${TOOL}/bin/${TARGET}${API}-clang']
          cpp = ['ccache', '${TOOL}/bin/${TARGET}${API}-clang++']
          ar = '${TOOL}/bin/llvm-ar'
          strip = '${TOOL}/bin/llvm-strip'
          pkg-config = '/usr/bin/pkg-config'
          # IMPORTANT: qmake is TARGET (Android) and belongs in the CROSS file
          qmake6 = '${QT_ANDROID_DIR}/bin/qmake6'
          qmake  = '${QT_ANDROID_DIR}/bin/qmake6'

          [built-in options]
          c_args = ['-fPIC', '--sysroot=${TOOL}/sysroot']
          cpp_args = ['-fPIC', '--sysroot=${TOOL}/sysroot']
          c_link_args = ['--sysroot=${TOOL}/sysroot']
          cpp_link_args = ['--sysroot=${TOOL}/sysroot']

          [host_machine]
          system = 'android'
          cpu_family = 'aarch64'
          cpu = 'aarch64'
          endian = 'little'

          [properties]
          needs_exe_wrapper = true
          sys_root = '${TOOL}/sysroot'
          EOF
          cat android-aarch64.ini

      - name: Create Meson native file for host Qt tools
        working-directory: ${{ github.workspace }}
        run: |
          cat > native-qt.ini <<EOF
          [binaries]
          moc      = '${QT_HOST_DIR}/libexec/moc'
          uic      = '${QT_HOST_DIR}/bin/uic'
          rcc      = '${QT_HOST_DIR}/bin/rcc'
          qsb      = '${QT_HOST_DIR}/bin/qsb'
          qtpaths6 = '${QT_HOST_DIR}/bin/qtpaths6'
          cmake    = '/usr/bin/cmake'
          pkg-config = '/usr/bin/pkg-config'
          EOF
          cat native-qt.ini

      # ---------- GSTREAMER ----------
      - name: Configure & build GStreamer with qt6qmlgl
        run: |
          set -eux
          export PATH="${QT_ANDROID_DIR}/bin:${QT_HOST_DIR}/bin:${QT_HOST_DIR}/libexec:${PATH}"
          export QT_HOST_PATH="${QT_HOST_DIR}"
          # Safe even when LD_LIBRARY_PATH is unset (because of `set -u`)
          export LD_LIBRARY_PATH="${QT_HOST_DIR}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

          which qmake6
          qmake6 -query QT_INSTALL_PREFIX
          qtpaths6 -query QT_HOST_BINS || true
          which qsb
          qsb --version || true
          qmake6 -v || true

          rm -rf build-android-a64
          # Force the pip Meson, not /usr/bin/meson
          python3 -m mesonbuild.mesonmain setup build-android-a64 \
            --prefix "$PREFIX" \
            --cross-file "$GITHUB_WORKSPACE/android-aarch64.ini" \
            --native-file "$GITHUB_WORKSPACE/native-qt.ini" \
            --default-library=static \
            $MESON_OPTIONS \
            -Dqt-method=auto \
            -Dqt:qt_host_path="$QT_HOST_DIR" \
            -Dqt:cmake_module_path="$QT_ANDROID_DIR/lib/cmake;$QT_ANDROID_DIR/lib/cmake/Qt6"

          ninja -C build-android-a64 -j"$(nproc)"
          ninja -C build-android-a64 install

      - name: Verify artifacts
        run: |
          set -eux
          test -f "${PREFIX}/lib/libgstreamer-full-1.0.a"
          ls -l "${PREFIX}/lib/gstreamer-1.0" | grep -Ei 'qml6|qmlgl|qt6' || true
          PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig" pkg-config --modversion gstreamer-full-1.0 || true

      - name: ccache stats
        run: ccache --show-stats || true

      - name: Package artifacts
        run: |
          tar -C "${PREFIX}/.." -czf "${{ github.workspace }}/gst-android-aarch64.tar.gz" "$(basename "${PREFIX}")"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gst-android-aarch64
          path: gst-android-aarch64.tar.gz
          if-no-files-found: error
